---
$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.38.0/schema/markdownlint-config-schema.json
extends: markdownlint/style/prettier
MD026:
  punctuation: .,;:。，；：！
MD033:
  allowed_elements:
    - nobr
    - summary
    - details
MD046:
  style: fenced
