---
$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.38.0/schema/markdownlint-config-schema.json
extends: markdownlint/style/prettier
MD026:
  punctuation: .,;:。，；：！
MD033:
  allowed_elements:
    - nobr
MD046:
  style: fenced
"search-replace":
  rules:
    - name: no-tickbox-hard-space
      message: "tick box list items must contain a single soft space"
      searchPattern: "/- \\[(?! )\\s\\] /g"
      replace: "- [ ] "
