---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: Run the linter
        run: ./lint
      - name: Check the diagram
        run: ./diagram --check
